### PR TITLE
fix(webpack-ui): remove dependency on licensed non-open-source 'highcharts'

### PR DESCRIPTION
**Pull request by kellogg92**
The [highcharts](https://github.com/highcharts/highcharts) library is not open-source or free. It was flagged by my team's dependency tracker, and that's made it impossible for us to use Statoscope.

Statoscope is so much more advanced and helpful than the other bundle analyzers I've found, so we really want to use it.

If a chart view is necessary, there are several open-source alternatives to 'highcharts' that should be easy to add, for instance [D3](https://github.com/d3/d3) is a well-known data-visualization library. Another option would be to make the `chart` view into an extension somehow, but I can see that might be complicated due to the bundling being done before package publication.

### CODE REVIEW

**Comment by smelukov** [comment]
@kellogg92  Thanks for your PR.
I'll replace highcharts with something else (chart.js maybe).
I'm on vacation now therefore it may take few days.
For now I'll merge your PR and publish an alpha-version with your fix to let you use Statoscope without highcharts

**Comment by smelukov** [comment]
@kellogg92 published it 5.23.1-alpha.0

**Comment by kellogg92** [comment]
Thank you! The updated version looks like it works for me!

**Comment by smelukov** [comment]
@kellogg92 highcharts was replaced by [chartjs](https://www.chartjs.org/) in [Statoscope v5.24.0](https://github.com/statoscope/statoscope/releases/tag/v5.24.0)

**Pull request merged**
